In [2]:
import pandas as pd

summary_path = "/home/tunguyen/energyfl/outputs4/experiment_summary.csv"
summary = pd.read_csv(summary_path)
summary.T

0  \
result_folder                             /root/energyfl/outputs4/2024-02-21_10-39-55   
energy_file                                                                energy.csv   
server                                                 estats-10.toulouse.grid5000.fr   
sleep_duration                                                                     30   
neuralnet                                                            MobileNetV3Small   
strategy                                                                      fedadam   
optimizer                                                                         SGD   
estats-11                                                       [0 1 2 3 4 5 6 7 8 9]   
estats-12                                             [10 11 12 13 14 15 16 17 18 19]   
estats-2                                              [20 21 22 23 24 25 26 27 28 29]   
estats-3                                              [30 31 32 33 34 35 36 37 38 39]   
estats-4                                              [40 41 42 43 44 45 46 47 48 49]   
estats-5                                              [50 51 52 53 54 55 56 57 58 59]   
estats-6                                              [60 61 62 63 64 65 66 67 68 69]   
estats-7                                              [70 71 72 73 74 75 76 77 78 79]   
estats-8                                              [80 81 82 83 84 85 86 87 88 89]   
estats-9                                              [90 91 92 93 94 95 96 97 98 99]   
timestamps.start_experiment_before_sleep                   2024-02-21_10-40-06_513718   
timestamps.start_experiment                                2024-02-21_10-40-36_544021   
timestamps.end_experiment                                  2024-02-21_10-47-16_347868   
timestamps.end_experiment_after_sleep                      2024-02-21_10-47-46_378356   
params.num_rounds                                                                1000   
params.num_clients_per_round_fit                                                    2   
params.num_clients_per_round_eval                                                   2   
params.min_fit_clients                                                             10   
params.fraction_fit                                                               0.1   
params.fraction_evaluate                                                          0.5   
params.wait_round                                                                  10   
params.lr                                                                    0.031623   
data.data_name                                                                CIFAR10   
data.batch_size                                                                    50   
data.validation_split                                                              20   
data.num_clients                                                                  100   
data.alpha                                                                        0.1   
data.partition                                                             label_skew   
client.lr                                                                        0.01   
client.local_epochs                                                                 3   
client.decay_rate                                                                   1   
client.decay_steps                                                                  1   
comm.host                                                               172.16.121.10   
comm.port                                                                        8080   

                                                                                    1  \
result_folder                             /root/energyfl/outputs4/2024-02-21_10-47-51   
energy_file                                                                energy.csv   
server                                                 estats-10.toulouse.grid

In [36]:
result_path = "/root/energyfl/outputs/2024-02-15_20-13-16"
summary[summary["result_folder"] == result_path]["estats-8"].iloc[0]

'[0 1 2 3 4]'

In [3]:
from utils.process_results import EnergyResult
energy = EnergyResult("/home/tunguyen/energyfl/outputs", 4, "2024-02-15_20-13-16")

In [4]:
energy.m

In [3]:
import numpy as np
np.array_split(np.arange(100),9)

[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]),
 array([23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33]),
 array([34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44]),
 array([45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55]),
 array([56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66]),
 array([67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77]),
 array([78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88]),
 array([89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])]